### ISSUE TITLE
Check values in tests and add to, correct or improve

### ISSUE THREAD

**Issue by adamhsparks** [gabrielblain/PowerSDI#27]
@gabrielblain, there are several superficial tests where I only test that the result is the expected structure not the expected values.

In others, I've assumed that the values we see are what's expected.

If the package is returning the correct values for all of the functions, I will endeavour to add more tests to validate against values to ensure that the functions are doing what we expect.

**Comment by gabrielblain** [comment]
Hi Adam,
I ran all the functions of our package.
They are returning the correct values :).
There is one (not so important) thing that could be improved to be more
consistent with the theory behind drought assessments based on standardized
drought indices.
The example of the ScientSDI function is:
ScientSDI(
  lon = -47.3,
  lat = -22.87,
  start.date = "2015-01-01",
  end.date = "2022-12-31",
  TS = 1,
  Good = "no"
)
I had to set this relatively short period (2015 to 2022) in order the
decrease the running time of this example (as asked by CRAN; <5 seconds).
Since it is just an example of how to run the function, I thought that it
was acceptable.
However, since you improved our package, do you think that it is possible
to make this period longer? I mean:
 ScientSDI(
  lon = -47.3,
  lat = -22.87,
  start.date = "1993-01-01",
  end.date = "2022-12-31",
  TS = 1,
  Good = "no"
)
If it is not possible, that's ok. In the vignette, we set a suitable period
(longer than 30 years).
Best wishes
Gabriel

Em dom., 15 de out. de 2023 às 00:24, Adam H. Sparks <
***@***.***> escreveu:

**Comment by adamhsparks** [comment]
Hi Gabriel,
Thanks for the confirmation. I’ll improve the tests by checking more values in the outputs.

Re: ScientSDI example, absolutely! I’ve sent that in the latest PR.

We’re getting close now, I will finish the tests and then I think it’s ready for CRAN or software review with rOpenSci if you wish.

Best,
Adam

**Comment by adamhsparks** [comment]
This is intended to be closed with, https://github.com/gabrielblain/PowerSDI/pull/28 pending @gabrielblain's review and confirmation

**Comment by adamhsparks** [comment]
Closed with https://github.com/gabrielblain/PowerSDI/pull/32
